import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono",
});

export const metadata = {
  title: "create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const className = `${jetbrainsMono.variable} font-primary`;
  return (
    <html lang="en">
      <body className={className}>
        <Header />

        {children}
      </body>
    </html>
  );
}
